-- Add missing columns to Item table
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "sku" TEXT;
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "costPrice" DOUBLE PRECISION;
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "sellingPrice" DOUBLE PRECISION;
